version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.15.3

    working_directory: ~/repo
    
    branches:
      only:
      - master
      - develop
      - /ft-.*/

    steps:
        - attach_workspace:
            at: ~/repo

        - checkout

        # Setup Code Climate test-reporter
        - run:
            name: Setup Code Climate test-reporter
            command: |
                # download test reporter as a static binary
                curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                chmod +x ./cc-test-reporter

        - run:
            name: Show the current branch
            command: echo ${CIRCLE_BRANCH}

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run:
            name: Setup Dependencies
            command: yarn install

        - save_cache:
            paths:
            - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run:
            name: Testing
            command: |
                # notify Code Climate of a pending test report using `before-build`
                ./cc-test-reporter before-build
                # run tests with coverage
                yarn coverage
                # upload coverage to code climate using `after-build`
                ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
                ./cc-test-reporter upload-coverage

        - store_artifacts:
            path: ./coverage/lcov.info
            prefix: tests

        - store_artifacts:
            path: coverage
            prefix: coverage
